### ISSUE TITLE
执行原理

### ISSUE THREAD

**Issue by ideamean** [george518/PPGo_Job#19]
1. 请问这个定时任务的执行原理是什么？从本地远程通过ssh执行任务的命令吗？
2. 如果任务执行过程中重启进程，是否会影响任务的正常执行？

**Comment by george518** [comment]
1、通过ssh执行任务命令，并将任务命令执行结果返回回来。当然执行本地任务不需要使用ssh了
2、任务执行过程中重启，不会影响已经执行任务的正常执行。每次重启，会将需要执行的任务加入执行队列。
