### ISSUE TITLE
Hello 从老版本的升级到  2.0 有升级指南吗 

### ISSUE THREAD

**Issue by wujunze** [george518/PPGo_Job#33]
Hello 从老版本的升级到  2.0 有升级指南吗

**Comment by george518** [comment]
升级比较简单，所以没写指南。升级步骤如下。
1、将老版的数据库里的表结构与新版对比一下，有些表需要新增，也有新增字段和修改字段的。
2、将老版数据库按照新版数据库修改，新增字段默认值就好。
3、将老版本的系统编译运行或者直接下载二进制包，启动就好。

数据库比较繁琐一些

**Comment by wujunze** [comment]
OK THX
